// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgZ0FHvHq-rEcE-T1_WNTSXY_8xmow8qg',
    appId: '1:619832864974:web:eef0afd44f1487c509209f',
    messagingSenderId: '619832864974',
    projectId: 'myapp-2bd7a',
    authDomain: 'myapp-2bd7a.firebaseapp.com',
    storageBucket: 'myapp-2bd7a.appspot.com',
    measurementId: 'G-1TDZ1VYHLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3bxEVaGzRRrVcwq7vRYBOSzFhxh4rKBE',
    appId: '1:619832864974:android:108ddc03c68f7c4509209f',
    messagingSenderId: '619832864974',
    projectId: 'myapp-2bd7a',
    storageBucket: 'myapp-2bd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Z8z8n8SLRJWLcnwJwGarpqIGv6EE_qQ',
    appId: '1:619832864974:ios:05dd927197a92fa309209f',
    messagingSenderId: '619832864974',
    projectId: 'myapp-2bd7a',
    storageBucket: 'myapp-2bd7a.appspot.com',
    iosClientId: '619832864974-18glppbvl3u94bq5d8hn1tf09flu5t4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Z8z8n8SLRJWLcnwJwGarpqIGv6EE_qQ',
    appId: '1:619832864974:ios:05dd927197a92fa309209f',
    messagingSenderId: '619832864974',
    projectId: 'myapp-2bd7a',
    storageBucket: 'myapp-2bd7a.appspot.com',
    iosClientId: '619832864974-18glppbvl3u94bq5d8hn1tf09flu5t4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
